changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Changes 🛠
      labels:
        - change
    - title: Bugs? No more! 🐞
      labels:
        - bug
    - title: Unreadable code? Should be better now 📝
      labels:
        - documentation
    - title: Other Changes 🛠
      labels:
        - "*"
    - title: Milestones
      milestones:
        - "*"
